## default connection pool
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mydb
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
config:
  location: "emp default"